### ISSUE TITLE
Not working with Tailwindcss 2.0.2

### ISSUE THREAD

**Issue by StephanLoewe** [jan-dh/figma-tailwindcss#12]
In tailwindcss v2.0.2
`import theme from './theme';`
does not work, because import statements are not allowed.
What worked for me was:
`let theme = require('./theme')`
In that case in the given theme.js the last line should be
`module.exports = theme`
instead of
`export default theme;`

Or am I doing something wrong? Would be cool just to replace the theme.js in the folder for design updates fromg the figma file.

**Comment by jan-dh** [comment]
Haven't tried tailwind 2.x but I'm guessing the theme variable is already declared in the tailwind config object. You can name the theme import whatever you want since it's a default export, for example:

```
import myTheme from './theme`
```

**Comment by jan-dh** [comment]
Going to close this since this isn't really an issue with the plugin. If you have any other questions, feel free to reach out to me.

**Comment by jan-dh** [comment]
@moracabanas 

if you remove the export statement from the generated file you can import it in your tailwind config like so:

```
const myTheme = require('./theme');
```

the `import`syntax gives some errors but it does work.

Once you have the imported myTheme variable (don't use theme since that's a key already existing in your tailwind config), you have to do it per key. For example with the spread operator (adding your values to some defaults):

```
 fontFamily: {
      sans: [
        'system-ui',
         ....
      ],
      serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: ['Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
      ...myTheme.fontFamily
    },
```

That's a nice way to use TailwindCSS's default values (you can output a tailwind config with all the values in it using `npx tailwindcss init --full`) and extend them with your own from the theme file.
