### ISSUE TITLE
[Feature] Additional exports

### ISSUE THREAD

**Issue by JesusTheHun** [jan-dh/figma-tailwindcss#14]
As you mention in your readme you plan to add more exports, here are some requests : 

* `border-radius`
* `padding`
* `marging`
* `leading`
* `gradient` (exported as components, I know you've rejected a request regarding components before, this case has a much smaller scope)

Edit :
* `shadow`

**Comment by JesusTheHun** [comment]
Also `shadow`

**Comment by jan-dh** [comment]
Thanks for the input. I'll make separate issues for all of the above to discuss the possible implementation. Some of them were on my list but I haven't found a decent way to implement.

**Comment by jan-dh** [comment]
A small update on this: I'm working on an update to implement `border-radius` and `shadows`. `Leading` is something that's also still on the radar.

Padding and margins however are a bit more tricky, since it's hard to calculate all spaces. There are a lot of spaces that don't need to be included in to your css (horizontal spacing for centered items for example). I also can't account for extra whitespace created by line-height etc.

**Comment by jan-dh** [comment]
New release with box-shadow support. Going to close this and track each prop in a different issue
